FROM golang:latest

RUN mkdir /build
WORKDIR /build

RUN export GO111MODULE=on
RUN go install github.com/OsbornCollins/SysAdminProject/main@latest
RUN cd /build && git clone https://github.com/OsbornCollins/SysAdminProject.git

RUN cd /build/SysAdminProject/main && go build

EXPOSE 8080

ENTRYPOINT [ "/build/SysAdminProject/main/main" ]